// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetInterval(): $CancellablePromise<number> {
    return $Call.ByID(1710349940);
}

export function GetSnapshot(): $CancellablePromise<$models.SnapshotResult> {
    return $Call.ByID(3495076969).then(($result: any) => {
        return $$createType0($result);
    });
}

export function IsRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(611305362);
}

export function RefreshNow(): $CancellablePromise<boolean> {
    return $Call.ByID(3645704754);
}

export function SetInterval(intervalMs: number): $CancellablePromise<boolean> {
    return $Call.ByID(3414625240, intervalMs);
}

export function Start(intervalMs: number): $CancellablePromise<boolean> {
    return $Call.ByID(2642701717, intervalMs);
}

export function Stop(): $CancellablePromise<boolean> {
    return $Call.ByID(1111007783);
}

// Private type creation functions
const $$createType0 = $models.SnapshotResult.createFrom;
