// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetInterval(): $CancellablePromise<number> {
    return $Call.ByName("github.com/zwb/network-ports/services/monitor.Monitor.GetInterval");
}

export function GetSnapshot(): $CancellablePromise<$models.SnapshotResult> {
    return $Call.ByName("github.com/zwb/network-ports/services/monitor.Monitor.GetSnapshot").then(($result: any) => {
        return $$createType0($result);
    });
}

export function IsRunning(): $CancellablePromise<boolean> {
    return $Call.ByName("github.com/zwb/network-ports/services/monitor.Monitor.IsRunning");
}

export function RefreshNow(): $CancellablePromise<boolean> {
    return $Call.ByName("github.com/zwb/network-ports/services/monitor.Monitor.RefreshNow");
}

export function SetInterval(intervalMs: number): $CancellablePromise<boolean> {
    return $Call.ByName("github.com/zwb/network-ports/services/monitor.Monitor.SetInterval", intervalMs);
}

export function Start(intervalMs: number): $CancellablePromise<boolean> {
    return $Call.ByName("github.com/zwb/network-ports/services/monitor.Monitor.Start", intervalMs);
}

export function Stop(): $CancellablePromise<boolean> {
    return $Call.ByName("github.com/zwb/network-ports/services/monitor.Monitor.Stop");
}

// Private type creation functions
const $$createType0 = $models.SnapshotResult.createFrom;
