// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Info {
    "pid": number;
    "ppid": number;
    "name": string;
    "path": string;
    "cmdLine": string;
    "user": string;
    "startTime": number;

    /** Creates a new Info instance. */
    constructor($$source: Partial<Info> = {}) {
        if (!("pid" in $$source)) {
            this["pid"] = 0;
        }
        if (!("ppid" in $$source)) {
            this["ppid"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("cmdLine" in $$source)) {
            this["cmdLine"] = "";
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("startTime" in $$source)) {
            this["startTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Info instance from a string or object.
     */
    static createFrom($$source: any = {}): Info {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Info($$parsedSource as Partial<Info>);
    }
}
