//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as monitor$0 from "../../../../wenit/NetstatUI/services/monitor/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as netstat$0 from "../../../../wenit/NetstatUI/services/netstat/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "conn:diff": $$createType0,
        "conn:full": $$createType2,
        "conn:stats": $$createType3,
        "geo:status": $$createType4,
    }));
}

// Private type creation functions
const $$createType0 = monitor$0.Diff.createFrom;
const $$createType1 = netstat$0.ConnInfo.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = monitor$0.Stats.createFrom;
const $$createType4 = monitor$0.GeoStatus.createFrom;

configure();
