// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as monitor$0 from "../../../../wenit/NetstatUI/services/monitor/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as netstat$0 from "../../../../wenit/NetstatUI/services/netstat/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "conn:diff": monitor$0.Diff;
            "conn:error": string;
            "conn:full": netstat$0.ConnInfo[];
            "conn:stats": monitor$0.Stats;
        }
    }
}
