// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as kill$0 from "./services/kill/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as process$0 from "./services/process/models.js";

export function GetProcessDetail(pid: number): $CancellablePromise<process$0.Info> {
    return $Call.ByID(481530442, pid).then(($result: any) => {
        return $$createType0($result);
    });
}

export function KillProcess(pid: number): $CancellablePromise<kill$0.Result> {
    return $Call.ByID(3088885651, pid).then(($result: any) => {
        return $$createType1($result);
    });
}

export function OpenProcessFolder(pid: number): $CancellablePromise<void> {
    return $Call.ByID(1626926283, pid);
}

// Private type creation functions
const $$createType0 = process$0.Info.createFrom;
const $$createType1 = kill$0.Result.createFrom;
