// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ConnInfo {
    "key": string;
    "protocol": Protocol;
    "localAddr": string;
    "localPort": number;
    "remoteAddr": string;
    "remotePort": number;
    "state": State;
    "pid": number;
    "processName": string;
    "processPath": string;

    /** Creates a new ConnInfo instance. */
    constructor($$source: Partial<ConnInfo> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("protocol" in $$source)) {
            this["protocol"] = Protocol.$zero;
        }
        if (!("localAddr" in $$source)) {
            this["localAddr"] = "";
        }
        if (!("localPort" in $$source)) {
            this["localPort"] = 0;
        }
        if (!("remoteAddr" in $$source)) {
            this["remoteAddr"] = "";
        }
        if (!("remotePort" in $$source)) {
            this["remotePort"] = 0;
        }
        if (!("state" in $$source)) {
            this["state"] = State.$zero;
        }
        if (!("pid" in $$source)) {
            this["pid"] = 0;
        }
        if (!("processName" in $$source)) {
            this["processName"] = "";
        }
        if (!("processPath" in $$source)) {
            this["processPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnInfo($$parsedSource as Partial<ConnInfo>);
    }
}

export enum Protocol {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ProtocolTCP4 = "tcp4",
    ProtocolTCP6 = "tcp6",
    ProtocolUDP4 = "udp4",
    ProtocolUDP6 = "udp6",
};

export enum State {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StateUnknown = "UNKNOWN",
    StateClosed = "CLOSED",
    StateListen = "LISTEN",
    StateSynSent = "SYN_SENT",
    StateSynReceived = "SYN_RECEIVED",
    StateEstablished = "ESTABLISHED",
    StateFinWait1 = "FIN_WAIT_1",
    StateFinWait2 = "FIN_WAIT_2",
    StateCloseWait = "CLOSE_WAIT",
    StateClosing = "CLOSING",
    StateTimeWait = "TIME_WAIT",
    StateDeleteTCB = "DELETE_TCB",
    StateBound = "BOUND",
};
