// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as netstat$0 from "../netstat/models.js";

export class Diff {
    "added": netstat$0.ConnInfo[];
    "removed": string[];
    "updated": netstat$0.ConnInfo[];

    /** Creates a new Diff instance. */
    constructor($$source: Partial<Diff> = {}) {
        if (!("added" in $$source)) {
            this["added"] = [];
        }
        if (!("removed" in $$source)) {
            this["removed"] = [];
        }
        if (!("updated" in $$source)) {
            this["updated"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Diff instance from a string or object.
     */
    static createFrom($$source: any = {}): Diff {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("added" in $$parsedSource) {
            $$parsedSource["added"] = $$createField0_0($$parsedSource["added"]);
        }
        if ("removed" in $$parsedSource) {
            $$parsedSource["removed"] = $$createField1_0($$parsedSource["removed"]);
        }
        if ("updated" in $$parsedSource) {
            $$parsedSource["updated"] = $$createField2_0($$parsedSource["updated"]);
        }
        return new Diff($$parsedSource as Partial<Diff>);
    }
}

export class SnapshotResult {
    "conns": netstat$0.ConnInfo[];
    "stats": Stats;

    /** Creates a new SnapshotResult instance. */
    constructor($$source: Partial<SnapshotResult> = {}) {
        if (!("conns" in $$source)) {
            this["conns"] = [];
        }
        if (!("stats" in $$source)) {
            this["stats"] = (new Stats());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SnapshotResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SnapshotResult {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("conns" in $$parsedSource) {
            $$parsedSource["conns"] = $$createField0_0($$parsedSource["conns"]);
        }
        if ("stats" in $$parsedSource) {
            $$parsedSource["stats"] = $$createField1_0($$parsedSource["stats"]);
        }
        return new SnapshotResult($$parsedSource as Partial<SnapshotResult>);
    }
}

export class Stats {
    "total": number;
    "listen": number;
    "established": number;
    "udp": number;
    "filteredHits": number;

    /** Creates a new Stats instance. */
    constructor($$source: Partial<Stats> = {}) {
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("listen" in $$source)) {
            this["listen"] = 0;
        }
        if (!("established" in $$source)) {
            this["established"] = 0;
        }
        if (!("udp" in $$source)) {
            this["udp"] = 0;
        }
        if (!("filteredHits" in $$source)) {
            this["filteredHits"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Stats instance from a string or object.
     */
    static createFrom($$source: any = {}): Stats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Stats($$parsedSource as Partial<Stats>);
    }
}

// Private type creation functions
const $$createType0 = netstat$0.ConnInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = Stats.createFrom;
