// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetInterval(): $CancellablePromise<number> {
    return $Call.ByID(1186957896);
}

export function GetSnapshot(): $CancellablePromise<$models.SnapshotResult> {
    return $Call.ByID(4058836157).then(($result: any) => {
        return $$createType0($result);
    });
}

export function IsRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(3090077342);
}

export function RefreshNow(): $CancellablePromise<boolean> {
    return $Call.ByID(1877792526);
}

export function SetInterval(intervalMs: number): $CancellablePromise<boolean> {
    return $Call.ByID(3636284740, intervalMs);
}

export function Start(intervalMs: number): $CancellablePromise<boolean> {
    return $Call.ByID(222342489, intervalMs);
}

export function Stop(): $CancellablePromise<boolean> {
    return $Call.ByID(696220211);
}

// Private type creation functions
const $$createType0 = $models.SnapshotResult.createFrom;
